apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dockerdaemon
spec:
  selector:
    matchLabels:
      name: dind
  template:
    metadata:
      labels:
        name: dind
    spec:
      containers:
      - name: dind
        image: docker:18.05-dind
        securityContext:
          privileged: true
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        - name: dind-socket
          mountPath: /var/run/
      volumes:
      - name: dind-storage
        emptyDir: {}
      - name: dind-socket
        hostPath:
          path: /var/run/docker-dind
          type: DirectoryOrCreate
