apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: docker-build
spec:
  taskRef:
    name: docker
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/dlorenc/shellshocked
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: gcr.io/dlorenc-vmtest2/dockered